# quarto render --to all ; git add docs; git commit -am "genererar nya docs" ; git push

project:
  type: book
  output-dir: docs

book:
  title: "Huspärm Karlslund"
  subtitle: "Lindesberg Sällinge 2:4"
  author: "Tobias Hagberg"
  date: "2025-10-31"
  chapters:
    - index.qmd
    - summary.qmd
    - persongalleri.qmd
    - renovering.qmd
    - part: bilagor.qmd
      chapters:
      - linoljeförädling.qmd
      - färgtillverkning.qmd
      - recept-grok.qmd
    - references.qmd
  downloads: [pdf]

csl: apa.csl
bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    lang: sv
    toc: true
    toc-depth: 3
    toc-expand: 3
  pdf:
    documentclass: scrreprt
    papersize: a4
    toc: true
    number-sections: true
    colorlinks: true
    mainfont: 'Cardo Regular'
    sansfont: 'Cardo Bold'
    keep-tex: true
    include-in-header:
      text: |
        \usepackage{pdfpages}
        \usepackage{ragged2e}
        \usepackage{rotating}